name: snapvids_app
description: snapvids app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.7
  country_picker: ^2.0.23
  flutter_riverpod: ^2.4.10
  image_picker: ^1.0.7
  photo_manager: ^3.0.0
  dio: ^5.4.1
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.2
  flutter_easyloading: ^3.0.5

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#FFFFFF"
  color_dark: "#0C0F14"
  image: assets/images/splash_light.png
  image_dark: assets/images/splash_dark.png
  android_12:
    color: "#FFFFFF"
    color_dark: "#0C0F14"
    image: assets/images/splash_light.png
    image_dark: assets/images/splash_dark.png
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#0C0F14"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
