import 'package:flutter/material.dart';
import 'package:snapvids_app/common/config/dark_colors.dart';
import 'package:snapvids_app/common/config/light_colors.dart';
import 'package:snapvids_app/common/utils/coloors.dart';

extension ExtendedTheme on BuildContext {
  CustomThemeExtension get theme {
    return Theme.of(this).extension<CustomThemeExtension>()!;
  }
}

class CustomThemeExtension extends ThemeExtension<CustomThemeExtension> {
  static const lightMode = CustomThemeExtension(
    splashTopBgColor: Coloors.redLight,
    greyColor: Coloors.greyLight,
    blueColor: Coloors.blueLight,
    langBtnBgColor: Color(0xFFF7F8F1),
    langBtnHighlightColor: Color(0xFFE8E8ED),
    authAppbarTextColor: Coloors.redLight,
    photoIconBgColor: Color(0xFFF0F2F3),
    photoIconColor: Color(0xFF9DAAB3),
    border_1: LightColors.border_1,
    border_2: LightColors.border_2,
    border_3: LightColors.border_3,
    border_4: LightColors.border_4,
    fill_1: LightColors.fill_1,
    fill_2: LightColors.fill_2,
    fill_3: LightColors.fill_3,
    fill_4: LightColors.fill_4,
    text_1: LightColors.text_1,
    text_2: LightColors.text_2,
    text_3: LightColors.text_3,
    text_4: LightColors.text_4,
    background_1: LightColors.background_1,
    background_2: LightColors.background_2,
    background_3: LightColors.background_3,
    background_4: LightColors.background_4,
    red_1: LightColors.red_1,
    red_2: LightColors.red_2,
    red_3: LightColors.red_3,
    red_4: LightColors.red_4,
    red_5: LightColors.red_5,
    red_6: LightColors.red_6,
    red_7: LightColors.red_7,
    red_8: LightColors.red_8,
    red_9: LightColors.red_9,
    red_10: LightColors.red_10,
    orangeRed_1: LightColors.orangeRed_1,
    orangeRed_2: LightColors.orangeRed_2,
    orangeRed_3: LightColors.orangeRed_3,
    orangeRed_4: LightColors.orangeRed_4,
    orangeRed_5: LightColors.orangeRed_5,
    orangeRed_6: LightColors.orangeRed_6,
    orangeRed_7: LightColors.orangeRed_7,
    orangeRed_8: LightColors.orangeRed_8,
    orangeRed_9: LightColors.orangeRed_9,
    orangeRed_10: LightColors.orangeRed_10,
    orange_1: LightColors.orange_1,
    orange_2: LightColors.orange_2,
    orange_3: LightColors.orange_3,
    orange_4: LightColors.orange_4,
    orange_5: LightColors.orange_5,
    orange_6: LightColors.orange_6,
    orange_7: LightColors.orange_7,
    orange_8: LightColors.orange_8,
    orange_9: LightColors.orange_9,
    orange_10: LightColors.orange_10,
    gold_1: LightColors.gold_1,
    gold_2: LightColors.gold_2,
    gold_3: LightColors.gold_3,
    gold_4: LightColors.gold_4,
    gold_5: LightColors.gold_5,
    gold_6: LightColors.gold_6,
    gold_7: LightColors.gold_7,
    gold_8: LightColors.gold_8,
    gold_9: LightColors.gold_9,
    gold_10: LightColors.gold_10,
    yellow_1: LightColors.yellow_1,
    yellow_2: LightColors.yellow_2,
    yellow_3: LightColors.yellow_3,
    yellow_4: LightColors.yellow_4,
    yellow_5: LightColors.yellow_5,
    yellow_6: LightColors.yellow_6,
    yellow_7: LightColors.yellow_7,
    yellow_8: LightColors.yellow_8,
    yellow_9: LightColors.yellow_9,
    yellow_10: LightColors.yellow_10,
    lime_1: LightColors.lime_1,
    lime_2: LightColors.lime_2,
    lime_3: LightColors.lime_3,
    lime_4: LightColors.lime_4,
    lime_5: LightColors.lime_5,
    lime_6: LightColors.lime_6,
    lime_7: LightColors.lime_7,
    lime_8: LightColors.lime_8,
    lime_9: LightColors.lime_9,
    lime_10: LightColors.lime_10,
    green_1: LightColors.green_1,
    green_2: LightColors.green_2,
    green_3: LightColors.green_3,
    green_4: LightColors.green_4,
    green_5: LightColors.green_5,
    green_6: LightColors.green_6,
    green_7: LightColors.green_7,
    green_8: LightColors.green_8,
    green_9: LightColors.green_9,
    green_10: LightColors.green_10,
    cyan_1: LightColors.cyan_1,
    cyan_2: LightColors.cyan_2,
    cyan_3: LightColors.cyan_3,
    cyan_4: LightColors.cyan_4,
    cyan_5: LightColors.cyan_5,
    cyan_6: LightColors.cyan_6,
    cyan_7: LightColors.cyan_7,
    cyan_8: LightColors.cyan_8,
    cyan_9: LightColors.cyan_9,
    cyan_10: LightColors.cyan_10,
    blue_1: LightColors.blue_1,
    blue_2: LightColors.blue_2,
    blue_3: LightColors.blue_3,
    blue_4: LightColors.blue_4,
    blue_5: LightColors.blue_5,
    blue_6: LightColors.blue_6,
    blue_7: LightColors.blue_7,
    blue_8: LightColors.blue_8,
    blue_9: LightColors.blue_9,
    blue_10: LightColors.blue_10,
    arcoBlue_1: LightColors.arcoBlue_1,
    arcoBlue_2: LightColors.arcoBlue_2,
    arcoBlue_3: LightColors.arcoBlue_3,
    arcoBlue_4: LightColors.arcoBlue_4,
    arcoBlue_5: LightColors.arcoBlue_5,
    arcoBlue_6: LightColors.arcoBlue_6,
    arcoBlue_7: LightColors.arcoBlue_7,
    arcoBlue_8: LightColors.arcoBlue_8,
    arcoBlue_9: LightColors.arcoBlue_9,
    arcoBlue_10: LightColors.arcoBlue_10,
    purple_1: LightColors.purple_1,
    purple_2: LightColors.purple_2,
    purple_3: LightColors.purple_3,
    purple_4: LightColors.purple_4,
    purple_5: LightColors.purple_5,
    purple_6: LightColors.purple_6,
    purple_7: LightColors.purple_7,
    purple_8: LightColors.purple_8,
    purple_9: LightColors.purple_9,
    purple_10: LightColors.purple_10,
    pinkPurple_1: LightColors.pinkPurple_1,
    pinkPurple_2: LightColors.pinkPurple_2,
    pinkPurple_3: LightColors.pinkPurple_3,
    pinkPurple_4: LightColors.pinkPurple_4,
    pinkPurple_5: LightColors.pinkPurple_5,
    pinkPurple_6: LightColors.pinkPurple_6,
    pinkPurple_7: LightColors.pinkPurple_7,
    pinkPurple_8: LightColors.pinkPurple_8,
    pinkPurple_9: LightColors.pinkPurple_9,
    pinkPurple_10: LightColors.pinkPurple_10,
    magenta_1: LightColors.magenta_1,
    magenta_2: LightColors.magenta_2,
    magenta_3: LightColors.magenta_3,
    magenta_4: LightColors.magenta_4,
    magenta_5: LightColors.magenta_5,
    magenta_6: LightColors.magenta_6,
    magenta_7: LightColors.magenta_7,
    magenta_8: LightColors.magenta_8,
    magenta_9: LightColors.magenta_9,
    magenta_10: LightColors.magenta_10,
    gray_1: LightColors.gray_1,
    gray_2: LightColors.gray_2,
    gray_3: LightColors.gray_3,
    gray_4: LightColors.gray_4,
    gray_5: LightColors.gray_5,
    gray_6: LightColors.gray_6,
    gray_7: LightColors.gray_7,
    gray_8: LightColors.gray_8,
    gray_9: LightColors.gray_9,
    gray_10: LightColors.gray_10,
  );

  static const darkMode = CustomThemeExtension(
    splashTopBgColor: Coloors.redDark,
    greyColor: Coloors.greyDark,
    blueColor: Coloors.blueDark,
    langBtnBgColor: Color(0xFF182229),
    langBtnHighlightColor: Color(0xFF09141A),
    authAppbarTextColor: Coloors.redDark,
    photoIconBgColor: Color(0xFF283339),
    photoIconColor: Color(0xFF61717B),
    border_1: DarkColors.border_1,
    border_2: DarkColors.border_2,
    border_3: DarkColors.border_3,
    border_4: DarkColors.border_4,
    fill_1: DarkColors.fill_1,
    fill_2: DarkColors.fill_2,
    fill_3: DarkColors.fill_3,
    fill_4: DarkColors.fill_4,
    text_1: DarkColors.text_1,
    text_2: DarkColors.text_2,
    text_3: DarkColors.text_3,
    text_4: DarkColors.text_4,
    background_1: DarkColors.background_1,
    background_2: DarkColors.background_2,
    background_3: DarkColors.background_3,
    background_4: DarkColors.background_4,
    red_1: DarkColors.red_1,
    red_2: DarkColors.red_2,
    red_3: DarkColors.red_3,
    red_4: DarkColors.red_4,
    red_5: DarkColors.red_5,
    red_6: DarkColors.red_6,
    red_7: DarkColors.red_7,
    red_8: DarkColors.red_8,
    red_9: DarkColors.red_9,
    red_10: DarkColors.red_10,
    orangeRed_1: DarkColors.orangeRed_1,
    orangeRed_2: DarkColors.orangeRed_2,
    orangeRed_3: DarkColors.orangeRed_3,
    orangeRed_4: DarkColors.orangeRed_4,
    orangeRed_5: DarkColors.orangeRed_5,
    orangeRed_6: DarkColors.orangeRed_6,
    orangeRed_7: DarkColors.orangeRed_7,
    orangeRed_8: DarkColors.orangeRed_8,
    orangeRed_9: DarkColors.orangeRed_9,
    orangeRed_10: DarkColors.orangeRed_10,
    orange_1: DarkColors.orange_1,
    orange_2: DarkColors.orange_2,
    orange_3: DarkColors.orange_3,
    orange_4: DarkColors.orange_4,
    orange_5: DarkColors.orange_5,
    orange_6: DarkColors.orange_6,
    orange_7: DarkColors.orange_7,
    orange_8: DarkColors.orange_8,
    orange_9: DarkColors.orange_9,
    orange_10: DarkColors.orange_10,
    gold_1: DarkColors.gold_1,
    gold_2: DarkColors.gold_2,
    gold_3: DarkColors.gold_3,
    gold_4: DarkColors.gold_4,
    gold_5: DarkColors.gold_5,
    gold_6: DarkColors.gold_6,
    gold_7: DarkColors.gold_7,
    gold_8: DarkColors.gold_8,
    gold_9: DarkColors.gold_9,
    gold_10: DarkColors.gold_10,
    yellow_1: DarkColors.yellow_1,
    yellow_2: DarkColors.yellow_2,
    yellow_3: DarkColors.yellow_3,
    yellow_4: DarkColors.yellow_4,
    yellow_5: DarkColors.yellow_5,
    yellow_6: DarkColors.yellow_6,
    yellow_7: DarkColors.yellow_7,
    yellow_8: DarkColors.yellow_8,
    yellow_9: DarkColors.yellow_9,
    yellow_10: DarkColors.yellow_10,
    lime_1: DarkColors.lime_1,
    lime_2: DarkColors.lime_2,
    lime_3: DarkColors.lime_3,
    lime_4: DarkColors.lime_4,
    lime_5: DarkColors.lime_5,
    lime_6: DarkColors.lime_6,
    lime_7: DarkColors.lime_7,
    lime_8: DarkColors.lime_8,
    lime_9: DarkColors.lime_9,
    lime_10: DarkColors.lime_10,
    green_1: DarkColors.green_1,
    green_2: DarkColors.green_2,
    green_3: DarkColors.green_3,
    green_4: DarkColors.green_4,
    green_5: DarkColors.green_5,
    green_6: DarkColors.green_6,
    green_7: DarkColors.green_7,
    green_8: DarkColors.green_8,
    green_9: DarkColors.green_9,
    green_10: DarkColors.green_10,
    cyan_1: DarkColors.cyan_1,
    cyan_2: DarkColors.cyan_2,
    cyan_3: DarkColors.cyan_3,
    cyan_4: DarkColors.cyan_4,
    cyan_5: DarkColors.cyan_5,
    cyan_6: DarkColors.cyan_6,
    cyan_7: DarkColors.cyan_7,
    cyan_8: DarkColors.cyan_8,
    cyan_9: DarkColors.cyan_9,
    cyan_10: DarkColors.cyan_10,
    blue_1: DarkColors.blue_1,
    blue_2: DarkColors.blue_2,
    blue_3: DarkColors.blue_3,
    blue_4: DarkColors.blue_4,
    blue_5: DarkColors.blue_5,
    blue_6: DarkColors.blue_6,
    blue_7: DarkColors.blue_7,
    blue_8: DarkColors.blue_8,
    blue_9: DarkColors.blue_9,
    blue_10: DarkColors.blue_10,
    arcoBlue_1: DarkColors.arcoBlue_1,
    arcoBlue_2: DarkColors.arcoBlue_2,
    arcoBlue_3: DarkColors.arcoBlue_3,
    arcoBlue_4: DarkColors.arcoBlue_4,
    arcoBlue_5: DarkColors.arcoBlue_5,
    arcoBlue_6: DarkColors.arcoBlue_6,
    arcoBlue_7: DarkColors.arcoBlue_7,
    arcoBlue_8: DarkColors.arcoBlue_8,
    arcoBlue_9: DarkColors.arcoBlue_9,
    arcoBlue_10: DarkColors.arcoBlue_10,
    purple_1: DarkColors.purple_1,
    purple_2: DarkColors.purple_2,
    purple_3: DarkColors.purple_3,
    purple_4: DarkColors.purple_4,
    purple_5: DarkColors.purple_5,
    purple_6: DarkColors.purple_6,
    purple_7: DarkColors.purple_7,
    purple_8: DarkColors.purple_8,
    purple_9: DarkColors.purple_9,
    purple_10: DarkColors.purple_10,
    pinkPurple_1: DarkColors.pinkPurple_1,
    pinkPurple_2: DarkColors.pinkPurple_2,
    pinkPurple_3: DarkColors.pinkPurple_3,
    pinkPurple_4: DarkColors.pinkPurple_4,
    pinkPurple_5: DarkColors.pinkPurple_5,
    pinkPurple_6: DarkColors.pinkPurple_6,
    pinkPurple_7: DarkColors.pinkPurple_7,
    pinkPurple_8: DarkColors.pinkPurple_8,
    pinkPurple_9: DarkColors.pinkPurple_9,
    pinkPurple_10: DarkColors.pinkPurple_10,
    magenta_1: DarkColors.magenta_1,
    magenta_2: DarkColors.magenta_2,
    magenta_3: DarkColors.magenta_3,
    magenta_4: DarkColors.magenta_4,
    magenta_5: DarkColors.magenta_5,
    magenta_6: DarkColors.magenta_6,
    magenta_7: DarkColors.magenta_7,
    magenta_8: DarkColors.magenta_8,
    magenta_9: DarkColors.magenta_9,
    magenta_10: DarkColors.magenta_10,
    gray_1: DarkColors.gray_1,
    gray_2: DarkColors.gray_2,
    gray_3: DarkColors.gray_3,
    gray_4: DarkColors.gray_4,
    gray_5: DarkColors.gray_5,
    gray_6: DarkColors.gray_6,
    gray_7: DarkColors.gray_7,
    gray_8: DarkColors.gray_8,
    gray_9: DarkColors.gray_9,
    gray_10: DarkColors.gray_10,
  );

  /// Todo: 待删除
  final Color? splashTopBgColor;
  final Color? greyColor;
  final Color? blueColor;
  final Color? langBtnBgColor;
  final Color? langBtnHighlightColor;
  final Color? authAppbarTextColor;
  final Color? photoIconBgColor;
  final Color? photoIconColor;

  /// 边框颜色
  final Color? border_1;
  final Color? border_2;
  final Color? border_3;
  final Color? border_4;

  /// 填充颜色
  final Color? fill_1;
  final Color? fill_2;
  final Color? fill_3;
  final Color? fill_4;

  /// 文字颜色
  final Color? text_1;
  final Color? text_2;
  final Color? text_3;
  final Color? text_4;

  /// 背景颜色
  final Color? background_1;
  final Color? background_2;
  final Color? background_3;
  final Color? background_4;

  /// 浪漫红
  final Color? red_1;
  final Color? red_2;
  final Color? red_3;
  final Color? red_4;
  final Color? red_5;
  final Color? red_6;
  final Color? red_7;
  final Color? red_8;
  final Color? red_9;
  final Color? red_10;

  /// 晚秋红
  final Color? orangeRed_1;
  final Color? orangeRed_2;
  final Color? orangeRed_3;
  final Color? orangeRed_4;
  final Color? orangeRed_5;
  final Color? orangeRed_6;
  final Color? orangeRed_7;
  final Color? orangeRed_8;
  final Color? orangeRed_9;
  final Color? orangeRed_10;

  /// 活力橙
  final Color? orange_1;
  final Color? orange_2;
  final Color? orange_3;
  final Color? orange_4;
  final Color? orange_5;
  final Color? orange_6;
  final Color? orange_7;
  final Color? orange_8;
  final Color? orange_9;
  final Color? orange_10;

  /// 黄昏
  final Color? gold_1;
  final Color? gold_2;
  final Color? gold_3;
  final Color? gold_4;
  final Color? gold_5;
  final Color? gold_6;
  final Color? gold_7;
  final Color? gold_8;
  final Color? gold_9;
  final Color? gold_10;

  /// 柠檬黄
  final Color? yellow_1;
  final Color? yellow_2;
  final Color? yellow_3;
  final Color? yellow_4;
  final Color? yellow_5;
  final Color? yellow_6;
  final Color? yellow_7;
  final Color? yellow_8;
  final Color? yellow_9;
  final Color? yellow_10;

  /// 新生绿
  final Color? lime_1;
  final Color? lime_2;
  final Color? lime_3;
  final Color? lime_4;
  final Color? lime_5;
  final Color? lime_6;
  final Color? lime_7;
  final Color? lime_8;
  final Color? lime_9;
  final Color? lime_10;

  /// 仙野绿
  final Color? green_1;
  final Color? green_2;
  final Color? green_3;
  final Color? green_4;
  final Color? green_5;
  final Color? green_6;
  final Color? green_7;
  final Color? green_8;
  final Color? green_9;
  final Color? green_10;

  /// 碧涛青
  final Color? cyan_1;
  final Color? cyan_2;
  final Color? cyan_3;
  final Color? cyan_4;
  final Color? cyan_5;
  final Color? cyan_6;
  final Color? cyan_7;
  final Color? cyan_8;
  final Color? cyan_9;
  final Color? cyan_10;

  /// 海蔚蓝
  final Color? blue_1;
  final Color? blue_2;
  final Color? blue_3;
  final Color? blue_4;
  final Color? blue_5;
  final Color? blue_6;
  final Color? blue_7;
  final Color? blue_8;
  final Color? blue_9;
  final Color? blue_10;

  /// 极致蓝
  final Color? arcoBlue_1;
  final Color? arcoBlue_2;
  final Color? arcoBlue_3;
  final Color? arcoBlue_4;
  final Color? arcoBlue_5;
  final Color? arcoBlue_6;
  final Color? arcoBlue_7;
  final Color? arcoBlue_8;
  final Color? arcoBlue_9;
  final Color? arcoBlue_10;

  /// 暗夜紫
  final Color? purple_1;
  final Color? purple_2;
  final Color? purple_3;
  final Color? purple_4;
  final Color? purple_5;
  final Color? purple_6;
  final Color? purple_7;
  final Color? purple_8;
  final Color? purple_9;
  final Color? purple_10;

  /// 青春紫
  final Color? pinkPurple_1;
  final Color? pinkPurple_2;
  final Color? pinkPurple_3;
  final Color? pinkPurple_4;
  final Color? pinkPurple_5;
  final Color? pinkPurple_6;
  final Color? pinkPurple_7;
  final Color? pinkPurple_8;
  final Color? pinkPurple_9;
  final Color? pinkPurple_10;

  /// 品红
  final Color? magenta_1;
  final Color? magenta_2;
  final Color? magenta_3;
  final Color? magenta_4;
  final Color? magenta_5;
  final Color? magenta_6;
  final Color? magenta_7;
  final Color? magenta_8;
  final Color? magenta_9;
  final Color? magenta_10;

  /// 中性灰
  final Color? gray_1;
  final Color? gray_2;
  final Color? gray_3;
  final Color? gray_4;
  final Color? gray_5;
  final Color? gray_6;
  final Color? gray_7;
  final Color? gray_8;
  final Color? gray_9;
  final Color? gray_10;

  const CustomThemeExtension({
    this.splashTopBgColor,
    this.greyColor,
    this.blueColor,
    this.langBtnBgColor,
    this.langBtnHighlightColor,
    this.authAppbarTextColor,
    this.photoIconBgColor,
    this.photoIconColor,
    this.border_1,
    this.border_2,
    this.border_3,
    this.border_4,
    this.fill_1,
    this.fill_2,
    this.fill_3,
    this.fill_4,
    this.text_1,
    this.text_2,
    this.text_3,
    this.text_4,
    this.background_1,
    this.background_2,
    this.background_3,
    this.background_4,
    this.red_1,
    this.red_2,
    this.red_3,
    this.red_4,
    this.red_5,
    this.red_6,
    this.red_7,
    this.red_8,
    this.red_9,
    this.red_10,
    this.orangeRed_1,
    this.orangeRed_2,
    this.orangeRed_3,
    this.orangeRed_4,
    this.orangeRed_5,
    this.orangeRed_6,
    this.orangeRed_7,
    this.orangeRed_8,
    this.orangeRed_9,
    this.orangeRed_10,
    this.orange_1,
    this.orange_2,
    this.orange_3,
    this.orange_4,
    this.orange_5,
    this.orange_6,
    this.orange_7,
    this.orange_8,
    this.orange_9,
    this.orange_10,
    this.gold_1,
    this.gold_2,
    this.gold_3,
    this.gold_4,
    this.gold_5,
    this.gold_6,
    this.gold_7,
    this.gold_8,
    this.gold_9,
    this.gold_10,
    this.yellow_1,
    this.yellow_2,
    this.yellow_3,
    this.yellow_4,
    this.yellow_5,
    this.yellow_6,
    this.yellow_7,
    this.yellow_8,
    this.yellow_9,
    this.yellow_10,
    this.lime_1,
    this.lime_2,
    this.lime_3,
    this.lime_4,
    this.lime_5,
    this.lime_6,
    this.lime_7,
    this.lime_8,
    this.lime_9,
    this.lime_10,
    this.green_1,
    this.green_2,
    this.green_3,
    this.green_4,
    this.green_5,
    this.green_6,
    this.green_7,
    this.green_8,
    this.green_9,
    this.green_10,
    this.cyan_1,
    this.cyan_2,
    this.cyan_3,
    this.cyan_4,
    this.cyan_5,
    this.cyan_6,
    this.cyan_7,
    this.cyan_8,
    this.cyan_9,
    this.cyan_10,
    this.blue_1,
    this.blue_2,
    this.blue_3,
    this.blue_4,
    this.blue_5,
    this.blue_6,
    this.blue_7,
    this.blue_8,
    this.blue_9,
    this.blue_10,
    this.arcoBlue_1,
    this.arcoBlue_2,
    this.arcoBlue_3,
    this.arcoBlue_4,
    this.arcoBlue_5,
    this.arcoBlue_6,
    this.arcoBlue_7,
    this.arcoBlue_8,
    this.arcoBlue_9,
    this.arcoBlue_10,
    this.purple_1,
    this.purple_2,
    this.purple_3,
    this.purple_4,
    this.purple_5,
    this.purple_6,
    this.purple_7,
    this.purple_8,
    this.purple_9,
    this.purple_10,
    this.pinkPurple_1,
    this.pinkPurple_2,
    this.pinkPurple_3,
    this.pinkPurple_4,
    this.pinkPurple_5,
    this.pinkPurple_6,
    this.pinkPurple_7,
    this.pinkPurple_8,
    this.pinkPurple_9,
    this.pinkPurple_10,
    this.magenta_1,
    this.magenta_2,
    this.magenta_3,
    this.magenta_4,
    this.magenta_5,
    this.magenta_6,
    this.magenta_7,
    this.magenta_8,
    this.magenta_9,
    this.magenta_10,
    this.gray_1,
    this.gray_2,
    this.gray_3,
    this.gray_4,
    this.gray_5,
    this.gray_6,
    this.gray_7,
    this.gray_8,
    this.gray_9,
    this.gray_10,
  });

  @override
  ThemeExtension<CustomThemeExtension> copyWith({
    Color? splashTopBgColor,
    Color? greyColor,
    Color? blueColor,
    Color? langBtnBgColor,
    Color? langBtnHighlightColor,
    Color? authAppbarTextColor,
    Color? photoIconBgColor,
    Color? photoIconColor,
    Color? border_1,
    Color? border_2,
    Color? border_3,
    Color? border_4,
    Color? fill_1,
    Color? fill_2,
    Color? fill_3,
    Color? fill_4,
    Color? text_1,
    Color? text_2,
    Color? text_3,
    Color? text_4,
    Color? background_1,
    Color? background_2,
    Color? background_3,
    Color? background_4,
    Color? red_1,
    Color? red_2,
    Color? red_3,
    Color? red_4,
    Color? red_5,
    Color? red_6,
    Color? red_7,
    Color? red_8,
    Color? red_9,
    Color? red_10,
    Color? orangeRed_1,
    Color? orangeRed_2,
    Color? orangeRed_3,
    Color? orangeRed_4,
    Color? orangeRed_5,
    Color? orangeRed_6,
    Color? orangeRed_7,
    Color? orangeRed_8,
    Color? orangeRed_9,
    Color? orangeRed_10,
    Color? orange_1,
    Color? orange_2,
    Color? orange_3,
    Color? orange_4,
    Color? orange_5,
    Color? orange_6,
    Color? orange_7,
    Color? orange_8,
    Color? orange_9,
    Color? orange_10,
    Color? gold_1,
    Color? gold_2,
    Color? gold_3,
    Color? gold_4,
    Color? gold_5,
    Color? gold_6,
    Color? gold_7,
    Color? gold_8,
    Color? gold_9,
    Color? gold_10,
    Color? yellow_1,
    Color? yellow_2,
    Color? yellow_3,
    Color? yellow_4,
    Color? yellow_5,
    Color? yellow_6,
    Color? yellow_7,
    Color? yellow_8,
    Color? yellow_9,
    Color? yellow_10,
    Color? lime_1,
    Color? lime_2,
    Color? lime_3,
    Color? lime_4,
    Color? lime_5,
    Color? lime_6,
    Color? lime_7,
    Color? lime_8,
    Color? lime_9,
    Color? lime_10,
    Color? green_1,
    Color? green_2,
    Color? green_3,
    Color? green_4,
    Color? green_5,
    Color? green_6,
    Color? green_7,
    Color? green_8,
    Color? green_9,
    Color? green_10,
    Color? cyan_1,
    Color? cyan_2,
    Color? cyan_3,
    Color? cyan_4,
    Color? cyan_5,
    Color? cyan_6,
    Color? cyan_7,
    Color? cyan_8,
    Color? cyan_9,
    Color? cyan_10,
    Color? blue_1,
    Color? blue_2,
    Color? blue_3,
    Color? blue_4,
    Color? blue_5,
    Color? blue_6,
    Color? blue_7,
    Color? blue_8,
    Color? blue_9,
    Color? blue_10,
    Color? arcoBlue_1,
    Color? arcoBlue_2,
    Color? arcoBlue_3,
    Color? arcoBlue_4,
    Color? arcoBlue_5,
    Color? arcoBlue_6,
    Color? arcoBlue_7,
    Color? arcoBlue_8,
    Color? arcoBlue_9,
    Color? arcoBlue_10,
    Color? purple_1,
    Color? purple_2,
    Color? purple_3,
    Color? purple_4,
    Color? purple_5,
    Color? purple_6,
    Color? purple_7,
    Color? purple_8,
    Color? purple_9,
    Color? purple_10,
    Color? pinkPurple_1,
    Color? pinkPurple_2,
    Color? pinkPurple_3,
    Color? pinkPurple_4,
    Color? pinkPurple_5,
    Color? pinkPurple_6,
    Color? pinkPurple_7,
    Color? pinkPurple_8,
    Color? pinkPurple_9,
    Color? pinkPurple_10,
    Color? magenta_1,
    Color? magenta_2,
    Color? magenta_3,
    Color? magenta_4,
    Color? magenta_5,
    Color? magenta_6,
    Color? magenta_7,
    Color? magenta_8,
    Color? magenta_9,
    Color? magenta_10,
    Color? gray_1,
    Color? gray_2,
    Color? gray_3,
    Color? gray_4,
    Color? gray_5,
    Color? gray_6,
    Color? gray_7,
    Color? gray_8,
    Color? gray_9,
    Color? gray_10,
  }) {
    return CustomThemeExtension(
      splashTopBgColor: splashTopBgColor ?? this.splashTopBgColor,
      greyColor: greyColor ?? this.greyColor,
      blueColor: blueColor ?? this.blueColor,
      langBtnBgColor: langBtnBgColor ?? this.langBtnBgColor,
      langBtnHighlightColor: langBtnHighlightColor ?? this.langBtnHighlightColor,
      authAppbarTextColor: authAppbarTextColor ?? this.authAppbarTextColor,
      photoIconBgColor: photoIconBgColor ?? this.photoIconBgColor,
      photoIconColor: photoIconColor ?? this.photoIconColor,
      border_1: border_1 ?? this.border_1,
      border_2: border_2 ?? this.border_2,
      border_3: border_3 ?? this.border_3,
      border_4: border_4 ?? this.border_4,
      fill_1: fill_1 ?? this.fill_1,
      fill_2: fill_2 ?? this.fill_2,
      fill_3: fill_3 ?? this.fill_3,
      fill_4: fill_4 ?? this.fill_4,
      text_1: text_1 ?? this.text_1,
      text_2: text_2 ?? this.text_2,
      text_3: text_3 ?? this.text_3,
      text_4: text_4 ?? this.text_4,
      background_1: background_1 ?? this.background_1,
      background_2: background_2 ?? this.background_2,
      background_3: background_3 ?? this.background_3,
      background_4: background_4 ?? this.background_4,
      red_1: red_1 ?? this.red_1,
      red_2: red_2 ?? this.red_2,
      red_3: red_3 ?? this.red_3,
      red_4: red_4 ?? this.red_4,
      red_5: red_5 ?? this.red_5,
      red_6: red_6 ?? this.red_6,
      red_7: red_7 ?? this.red_7,
      red_8: red_8 ?? this.red_8,
      red_9: red_9 ?? this.red_9,
      red_10: red_10 ?? this.red_10,
      orangeRed_1: orangeRed_1 ?? this.orangeRed_1,
      orangeRed_2: orangeRed_2 ?? this.orangeRed_2,
      orangeRed_3: orangeRed_3 ?? this.orangeRed_3,
      orangeRed_4: orangeRed_4 ?? this.orangeRed_4,
      orangeRed_5: orangeRed_5 ?? this.orangeRed_5,
      orangeRed_6: orangeRed_6 ?? this.orangeRed_6,
      orangeRed_7: orangeRed_7 ?? this.orangeRed_7,
      orangeRed_8: orangeRed_8 ?? this.orangeRed_8,
      orangeRed_9: orangeRed_9 ?? this.orangeRed_9,
      orangeRed_10: orangeRed_10 ?? this.orangeRed_10,
      orange_1: orange_1 ?? this.orange_1,
      orange_2: orange_2 ?? this.orange_2,
      orange_3: orange_3 ?? this.orange_3,
      orange_4: orange_4 ?? this.orange_4,
      orange_5: orange_5 ?? this.orange_5,
      orange_6: orange_6 ?? this.orange_6,
      orange_7: orange_7 ?? this.orange_7,
      orange_8: orange_8 ?? this.orange_8,
      orange_9: orange_9 ?? this.orange_9,
      orange_10: orange_10 ?? this.orange_10,
      gold_1: gold_1 ?? this.gold_1,
      gold_2: gold_2 ?? this.gold_2,
      gold_3: gold_3 ?? this.gold_3,
      gold_4: gold_4 ?? this.gold_4,
      gold_5: gold_5 ?? this.gold_5,
      gold_6: gold_6 ?? this.gold_6,
      gold_7: gold_7 ?? this.gold_7,
      gold_8: gold_8 ?? this.gold_8,
      gold_9: gold_9 ?? this.gold_9,
      gold_10: gold_10 ?? this.gold_10,
      yellow_1: yellow_1 ?? this.yellow_1,
      yellow_2: yellow_2 ?? this.yellow_2,
      yellow_3: yellow_3 ?? this.yellow_3,
      yellow_4: yellow_4 ?? this.yellow_4,
      yellow_5: yellow_5 ?? this.yellow_5,
      yellow_6: yellow_6 ?? this.yellow_6,
      yellow_7: yellow_7 ?? this.yellow_7,
      yellow_8: yellow_8 ?? this.yellow_8,
      yellow_9: yellow_9 ?? this.yellow_9,
      yellow_10: yellow_10 ?? this.yellow_10,
      lime_1: lime_1 ?? this.lime_1,
      lime_2: lime_2 ?? this.lime_2,
      lime_3: lime_3 ?? this.lime_3,
      lime_4: lime_4 ?? this.lime_4,
      lime_5: lime_5 ?? this.lime_5,
      lime_6: lime_6 ?? this.lime_6,
      lime_7: lime_7 ?? this.lime_7,
      lime_8: lime_8 ?? this.lime_8,
      lime_9: lime_9 ?? this.lime_9,
      lime_10: lime_10 ?? this.lime_10,
      green_1: green_1 ?? this.green_1,
      green_2: green_2 ?? this.green_2,
      green_3: green_3 ?? this.green_3,
      green_4: green_4 ?? this.green_4,
      green_5: green_5 ?? this.green_5,
      green_6: green_6 ?? this.green_6,
      green_7: green_7 ?? this.green_7,
      green_8: green_8 ?? this.green_8,
      green_9: green_9 ?? this.green_9,
      green_10: green_10 ?? this.green_10,
      cyan_1: cyan_1 ?? this.cyan_1,
      cyan_2: cyan_2 ?? this.cyan_2,
      cyan_3: cyan_3 ?? this.cyan_3,
      cyan_4: cyan_4 ?? this.cyan_4,
      cyan_5: cyan_5 ?? this.cyan_5,
      cyan_6: cyan_6 ?? this.cyan_6,
      cyan_7: cyan_7 ?? this.cyan_7,
      cyan_8: cyan_8 ?? this.cyan_8,
      cyan_9: cyan_9 ?? this.cyan_9,
      cyan_10: cyan_10 ?? this.cyan_10,
      blue_1: blue_1 ?? this.blue_1,
      blue_2: blue_2 ?? this.blue_2,
      blue_3: blue_3 ?? this.blue_3,
      blue_4: blue_4 ?? this.blue_4,
      blue_5: blue_5 ?? this.blue_5,
      blue_6: blue_6 ?? this.blue_6,
      blue_7: blue_7 ?? this.blue_7,
      blue_8: blue_8 ?? this.blue_8,
      blue_9: blue_9 ?? this.blue_9,
      blue_10: blue_10 ?? this.blue_10,
      arcoBlue_1: arcoBlue_1 ?? this.arcoBlue_1,
      arcoBlue_2: arcoBlue_2 ?? this.arcoBlue_2,
      arcoBlue_3: arcoBlue_3 ?? this.arcoBlue_3,
      arcoBlue_4: arcoBlue_4 ?? this.arcoBlue_4,
      arcoBlue_5: arcoBlue_5 ?? this.arcoBlue_5,
      arcoBlue_6: arcoBlue_6 ?? this.arcoBlue_6,
      arcoBlue_7: arcoBlue_7 ?? this.arcoBlue_7,
      arcoBlue_8: arcoBlue_8 ?? this.arcoBlue_8,
      arcoBlue_9: arcoBlue_9 ?? this.arcoBlue_9,
      arcoBlue_10: arcoBlue_10 ?? this.arcoBlue_10,
      purple_1: purple_1 ?? this.purple_1,
      purple_2: purple_2 ?? this.purple_2,
      purple_3: purple_3 ?? this.purple_3,
      purple_4: purple_4 ?? this.purple_4,
      purple_5: purple_5 ?? this.purple_5,
      purple_6: purple_6 ?? this.purple_6,
      purple_7: purple_7 ?? this.purple_7,
      purple_8: purple_8 ?? this.purple_8,
      purple_9: purple_9 ?? this.purple_9,
      purple_10: purple_10 ?? this.purple_10,
      pinkPurple_1: pinkPurple_1 ?? this.pinkPurple_1,
      pinkPurple_2: pinkPurple_2 ?? this.pinkPurple_2,
      pinkPurple_3: pinkPurple_3 ?? this.pinkPurple_3,
      pinkPurple_4: pinkPurple_4 ?? this.pinkPurple_4,
      pinkPurple_5: pinkPurple_5 ?? this.pinkPurple_5,
      pinkPurple_6: pinkPurple_6 ?? this.pinkPurple_6,
      pinkPurple_7: pinkPurple_7 ?? this.pinkPurple_7,
      pinkPurple_8: pinkPurple_8 ?? this.pinkPurple_8,
      pinkPurple_9: pinkPurple_9 ?? this.pinkPurple_9,
      pinkPurple_10: pinkPurple_10 ?? this.pinkPurple_10,
      magenta_1: magenta_1 ?? this.magenta_1,
      magenta_2: magenta_2 ?? this.magenta_2,
      magenta_3: magenta_3 ?? this.magenta_3,
      magenta_4: magenta_4 ?? this.magenta_4,
      magenta_5: magenta_5 ?? this.magenta_5,
      magenta_6: magenta_6 ?? this.magenta_6,
      magenta_7: magenta_7 ?? this.magenta_7,
      magenta_8: magenta_8 ?? this.magenta_8,
      magenta_9: magenta_9 ?? this.magenta_9,
      magenta_10: magenta_10 ?? this.magenta_10,
      gray_1: gray_1 ?? this.gray_1,
      gray_2: gray_2 ?? this.gray_2,
      gray_3: gray_3 ?? this.gray_3,
      gray_4: gray_4 ?? this.gray_4,
      gray_5: gray_5 ?? this.gray_5,
      gray_6: gray_6 ?? this.gray_6,
      gray_7: gray_7 ?? this.gray_7,
      gray_8: gray_8 ?? this.gray_8,
      gray_9: gray_9 ?? this.gray_9,
      gray_10: gray_10 ?? this.gray_10,
    );
  }

  @override
  ThemeExtension<CustomThemeExtension> lerp(ThemeExtension<CustomThemeExtension>? other, double t) {
    if (other is! CustomThemeExtension) return this;
    return CustomThemeExtension(
      splashTopBgColor: Color.lerp(splashTopBgColor, other.splashTopBgColor, t),
      greyColor: Color.lerp(greyColor, other.greyColor, t),
      blueColor: Color.lerp(blueColor, other.blueColor, t),
      langBtnBgColor: Color.lerp(langBtnBgColor, other.langBtnBgColor, t),
      langBtnHighlightColor: Color.lerp(langBtnHighlightColor, other.langBtnHighlightColor, t),
      authAppbarTextColor: Color.lerp(authAppbarTextColor, other.authAppbarTextColor, t),
      photoIconBgColor: Color.lerp(photoIconBgColor, other.photoIconBgColor, t),
      photoIconColor: Color.lerp(photoIconColor, other.photoIconColor, t),
      border_1: Color.lerp(border_1, other.border_1, t),
      border_2: Color.lerp(border_2, other.border_2, t),
      border_3: Color.lerp(border_3, other.border_3, t),
      border_4: Color.lerp(border_4, other.border_4, t),
      fill_1: Color.lerp(fill_1, other.fill_1, t),
      fill_2: Color.lerp(fill_2, other.fill_2, t),
      fill_3: Color.lerp(fill_3, other.fill_3, t),
      fill_4: Color.lerp(fill_4, other.fill_4, t),
      text_1: Color.lerp(text_1, other.text_1, t),
      text_2: Color.lerp(text_2, other.text_2, t),
      text_3: Color.lerp(text_3, other.text_3, t),
      text_4: Color.lerp(text_4, other.text_4, t),
      background_1: Color.lerp(background_1, other.background_1, t),
      background_2: Color.lerp(background_2, other.background_2, t),
      background_3: Color.lerp(background_3, other.background_3, t),
      background_4: Color.lerp(background_4, other.background_4, t),
      red_1: Color.lerp(red_1, other.red_1, t),
      red_2: Color.lerp(red_2, other.red_2, t),
      red_3: Color.lerp(red_3, other.red_3, t),
      red_4: Color.lerp(red_4, other.red_4, t),
      red_5: Color.lerp(red_5, other.red_5, t),
      red_6: Color.lerp(red_6, other.red_6, t),
      red_7: Color.lerp(red_7, other.red_7, t),
      red_8: Color.lerp(red_8, other.red_8, t),
      red_9: Color.lerp(red_9, other.red_9, t),
      red_10: Color.lerp(red_10, other.red_10, t),
      orangeRed_1: Color.lerp(orangeRed_1, other.orangeRed_1, t),
      orangeRed_2: Color.lerp(orangeRed_2, other.orangeRed_2, t),
      orangeRed_3: Color.lerp(orangeRed_3, other.orangeRed_3, t),
      orangeRed_4: Color.lerp(orangeRed_4, other.orangeRed_4, t),
      orangeRed_5: Color.lerp(orangeRed_5, other.orangeRed_5, t),
      orangeRed_6: Color.lerp(orangeRed_6, other.orangeRed_6, t),
      orangeRed_7: Color.lerp(orangeRed_7, other.orangeRed_7, t),
      orangeRed_8: Color.lerp(orangeRed_8, other.orangeRed_8, t),
      orangeRed_9: Color.lerp(orangeRed_9, other.orangeRed_9, t),
      orangeRed_10: Color.lerp(orangeRed_10, other.orangeRed_10, t),
      orange_1: Color.lerp(orange_1, other.orange_1, t),
      orange_2: Color.lerp(orange_2, other.orange_2, t),
      orange_3: Color.lerp(orange_3, other.orange_3, t),
      orange_4: Color.lerp(orange_4, other.orange_4, t),
      orange_5: Color.lerp(orange_5, other.orange_5, t),
      orange_6: Color.lerp(orange_6, other.orange_6, t),
      orange_7: Color.lerp(orange_7, other.orange_7, t),
      orange_8: Color.lerp(orange_8, other.orange_8, t),
      orange_9: Color.lerp(orange_9, other.orange_9, t),
      orange_10: Color.lerp(orange_10, other.orange_10, t),
      gold_1: Color.lerp(gold_1, other.gold_1, t),
      gold_2: Color.lerp(gold_2, other.gold_2, t),
      gold_3: Color.lerp(gold_3, other.gold_3, t),
      gold_4: Color.lerp(gold_4, other.gold_4, t),
      gold_5: Color.lerp(gold_5, other.gold_5, t),
      gold_6: Color.lerp(gold_6, other.gold_6, t),
      gold_7: Color.lerp(gold_7, other.gold_7, t),
      gold_8: Color.lerp(gold_8, other.gold_8, t),
      gold_9: Color.lerp(gold_9, other.gold_9, t),
      gold_10: Color.lerp(gold_10, other.gold_10, t),
      yellow_1: Color.lerp(yellow_1, other.yellow_1, t),
      yellow_2: Color.lerp(yellow_2, other.yellow_2, t),
      yellow_3: Color.lerp(yellow_3, other.yellow_3, t),
      yellow_4: Color.lerp(yellow_4, other.yellow_4, t),
      yellow_5: Color.lerp(yellow_5, other.yellow_5, t),
      yellow_6: Color.lerp(yellow_6, other.yellow_6, t),
      yellow_7: Color.lerp(yellow_7, other.yellow_7, t),
      yellow_8: Color.lerp(yellow_8, other.yellow_8, t),
      yellow_9: Color.lerp(yellow_9, other.yellow_9, t),
      yellow_10: Color.lerp(yellow_10, other.yellow_10, t),
      lime_1: Color.lerp(lime_1, other.lime_1, t),
      lime_2: Color.lerp(lime_2, other.lime_2, t),
      lime_3: Color.lerp(lime_3, other.lime_3, t),
      lime_4: Color.lerp(lime_4, other.lime_4, t),
      lime_5: Color.lerp(lime_5, other.lime_5, t),
      lime_6: Color.lerp(lime_6, other.lime_6, t),
      lime_7: Color.lerp(lime_7, other.lime_7, t),
      lime_8: Color.lerp(lime_8, other.lime_8, t),
      lime_9: Color.lerp(lime_9, other.lime_9, t),
      lime_10: Color.lerp(lime_10, other.lime_10, t),
      green_1: Color.lerp(green_1, other.green_1, t),
      green_2: Color.lerp(green_2, other.green_2, t),
      green_3: Color.lerp(green_3, other.green_3, t),
      green_4: Color.lerp(green_4, other.green_4, t),
      green_5: Color.lerp(green_5, other.green_5, t),
      green_6: Color.lerp(green_6, other.green_6, t),
      green_7: Color.lerp(green_7, other.green_7, t),
      green_8: Color.lerp(green_8, other.green_8, t),
      green_9: Color.lerp(green_9, other.green_9, t),
      green_10: Color.lerp(green_10, other.green_10, t),
      cyan_1: Color.lerp(cyan_1, other.cyan_1, t),
      cyan_2: Color.lerp(cyan_2, other.cyan_2, t),
      cyan_3: Color.lerp(cyan_3, other.cyan_3, t),
      cyan_4: Color.lerp(cyan_4, other.cyan_4, t),
      cyan_5: Color.lerp(cyan_5, other.cyan_5, t),
      cyan_6: Color.lerp(cyan_6, other.cyan_6, t),
      cyan_7: Color.lerp(cyan_7, other.cyan_7, t),
      cyan_8: Color.lerp(cyan_8, other.cyan_8, t),
      cyan_9: Color.lerp(cyan_9, other.cyan_9, t),
      cyan_10: Color.lerp(cyan_10, other.cyan_10, t),
      blue_1: Color.lerp(blue_1, other.blue_1, t),
      blue_2: Color.lerp(blue_2, other.blue_2, t),
      blue_3: Color.lerp(blue_3, other.blue_3, t),
      blue_4: Color.lerp(blue_4, other.blue_4, t),
      blue_5: Color.lerp(blue_5, other.blue_5, t),
      blue_6: Color.lerp(blue_6, other.blue_6, t),
      blue_7: Color.lerp(blue_7, other.blue_7, t),
      blue_8: Color.lerp(blue_8, other.blue_8, t),
      blue_9: Color.lerp(blue_9, other.blue_9, t),
      blue_10: Color.lerp(blue_10, other.blue_10, t),
      arcoBlue_1: Color.lerp(arcoBlue_1, other.arcoBlue_1, t),
      arcoBlue_2: Color.lerp(arcoBlue_2, other.arcoBlue_2, t),
      arcoBlue_3: Color.lerp(arcoBlue_3, other.arcoBlue_3, t),
      arcoBlue_4: Color.lerp(arcoBlue_4, other.arcoBlue_4, t),
      arcoBlue_5: Color.lerp(arcoBlue_5, other.arcoBlue_5, t),
      arcoBlue_6: Color.lerp(arcoBlue_6, other.arcoBlue_6, t),
      arcoBlue_7: Color.lerp(arcoBlue_7, other.arcoBlue_7, t),
      arcoBlue_8: Color.lerp(arcoBlue_8, other.arcoBlue_8, t),
      arcoBlue_9: Color.lerp(arcoBlue_9, other.arcoBlue_9, t),
      arcoBlue_10: Color.lerp(arcoBlue_10, other.arcoBlue_10, t),
      purple_1: Color.lerp(purple_1, other.purple_1, t),
      purple_2: Color.lerp(purple_2, other.purple_2, t),
      purple_3: Color.lerp(purple_3, other.purple_3, t),
      purple_4: Color.lerp(purple_4, other.purple_4, t),
      purple_5: Color.lerp(purple_5, other.purple_5, t),
      purple_6: Color.lerp(purple_6, other.purple_6, t),
      purple_7: Color.lerp(purple_7, other.purple_7, t),
      purple_8: Color.lerp(purple_8, other.purple_8, t),
      purple_9: Color.lerp(purple_9, other.purple_9, t),
      purple_10: Color.lerp(purple_10, other.purple_10, t),
      pinkPurple_1: Color.lerp(pinkPurple_1, other.pinkPurple_1, t),
      pinkPurple_2: Color.lerp(pinkPurple_2, other.pinkPurple_2, t),
      pinkPurple_3: Color.lerp(pinkPurple_3, other.pinkPurple_3, t),
      pinkPurple_4: Color.lerp(pinkPurple_4, other.pinkPurple_4, t),
      pinkPurple_5: Color.lerp(pinkPurple_5, other.pinkPurple_5, t),
      pinkPurple_6: Color.lerp(pinkPurple_6, other.pinkPurple_6, t),
      pinkPurple_7: Color.lerp(pinkPurple_7, other.pinkPurple_7, t),
      pinkPurple_8: Color.lerp(pinkPurple_8, other.pinkPurple_8, t),
      pinkPurple_9: Color.lerp(pinkPurple_9, other.pinkPurple_9, t),
      pinkPurple_10: Color.lerp(pinkPurple_10, other.pinkPurple_10, t),
      magenta_1: Color.lerp(magenta_1, other.magenta_1, t),
      magenta_2: Color.lerp(magenta_2, other.magenta_2, t),
      magenta_3: Color.lerp(magenta_3, other.magenta_3, t),
      magenta_4: Color.lerp(magenta_4, other.magenta_4, t),
      magenta_5: Color.lerp(magenta_5, other.magenta_5, t),
      magenta_6: Color.lerp(magenta_6, other.magenta_6, t),
      magenta_7: Color.lerp(magenta_7, other.magenta_7, t),
      magenta_8: Color.lerp(magenta_8, other.magenta_8, t),
      magenta_9: Color.lerp(magenta_9, other.magenta_9, t),
      magenta_10: Color.lerp(magenta_10, other.magenta_10, t),
      gray_1: Color.lerp(gray_1, other.gray_1, t),
      gray_2: Color.lerp(gray_2, other.gray_2, t),
      gray_3: Color.lerp(gray_3, other.gray_3, t),
      gray_4: Color.lerp(gray_4, other.gray_4, t),
      gray_5: Color.lerp(gray_5, other.gray_5, t),
      gray_6: Color.lerp(gray_6, other.gray_6, t),
      gray_7: Color.lerp(gray_7, other.gray_7, t),
      gray_8: Color.lerp(gray_8, other.gray_8, t),
      gray_9: Color.lerp(gray_9, other.gray_9, t),
      gray_10: Color.lerp(gray_10, other.gray_10, t),
    );
  }
}
